/*
 *  This Source Code Form is subject to the terms of the Mozilla Public License,
 *  v. 2.0. If a copy of the MPL was not distributed with this file, You can
 *  obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 *  the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *  <p>
 *  Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 *  graphic logo is a trademark of OpenMRS Inc.
 */

package org.openmrs.module.vxnaid.api.metadata;

import org.openmrs.module.cflcore.CFLConstants;
import org.openmrs.module.cflcore.api.util.GlobalPropertiesConstants;
import org.openmrs.module.metadatadeploy.bundle.VersionedMetadataBundle;

import static org.openmrs.module.metadatadeploy.bundle.CoreConstructors.globalProperty;

@SuppressWarnings("PMD.ExcessiveClassLength")
/** Sets initial values to various Global Properties. */
public class InitialGlobalPropertiesMetadata extends VersionedMetadataBundle {
  private static final String BIOMETRIC_ENABLE_BIOMETRIC_FEATURE_NAME =
      "biometric.enable.biometric.feature";
  private static final String BIOMETRIC_ENABLE_BIOMETRIC_FEATURE_DESC =
      "Specifies whether the biometric feature is "
          + "enables to store and match participant's biometrics.";
  private static final String BIOMETRIC_ENABLE_BIOMETRIC_FEATURE_INIT_VALUE = "false";

  private static final String BIOMETRIC_ENABLE_MFA_NAME = "biometric.enable.mfa";
  private static final String BIOMETRIC_ENABLE_MFA_DESC =
      "Search the  biometric database with participantId along with iris template";
  private static final String BIOMETRIC_ENABLE_MFA_INIT_VALUE = "true";

  private static final String BIOMETRIC_SERVER_URL_NAME = "biometric.server.url";
  private static final String BIOMETRIC_SERVER_URL_DESC = "Specifies the biometric server url";
  private static final String BIOMETRIC_SERVER_URL_INIT_VALUE =
      "Specifies the biometric server admin port";

  private static final String BIOMETRIC_ADMIN_PORT_NAME = "biometric.admin.port";
  private static final String BIOMETRIC_ADMIN_PORT_DESC =
      "Specifies the biometric server admin port";
  private static final String BIOMETRIC_ADMIN_PORT_INIT_VALUE = "24932";

  private static final String BIOMETRIC_CLIENT_PORT_NAME = "biometric.client.port";
  private static final String BIOMETRIC_CLIENT_PORT_DESC =
      "Specifies the biometric server client port";
  private static final String BIOMETRIC_CLIENT_PORT_INIT_VALUE = "25452";

  private static final String BIOMETRIC_EXTRACTOR_LICENSE_NAME = "biometric.extractor.license";
  private static final String BIOMETRIC_EXTRACTOR_LICENSE_DESC = "";
  private static final String BIOMETRIC_EXTRACTOR_LICENSE_INIT_VALUE = "";

  private static final String BIOMETRIC_IMPLEMENTATION_CONFIG_NAME =
      "biometric.implementation.config";
  private static final String BIOMETRIC_IMPLEMENTATION_CONFIG_DESC =
      "Specifies the config uuids required for this module";
  private static final String BIOMETRIC_IMPLEMENTATION_CONFIG_INIT_VALUE = "";

  private static final String BIOMETRIC_MATCHING_THRESHOLD_NAME = "biometric.matching.threshold";
  private static final String BIOMETRIC_MATCHING_THRESHOLD_DESC =
      "Specifies the biometric iris scan matching threshold";
  private static final String BIOMETRIC_MATCHING_THRESHOLD_INIT_VALUE = "60";

  private static final String BIOMETRIC_API_CONFIG_LOCALIZATION_NAME =
      "biometric.api.config.localization";
  private static final String BIOMETRIC_API_CONFIG_LOCALIZATION_DESC =
      "Specifies the biometric localization.";
  private static final String BIOMETRIC_API_CONFIG_LOCALIZATION_INIT_VALUE =
      "{\n"
          + "  \"localization\": {\n"
          + "    \"fr\": {\n"
          + "      \"State\": \"État\",\n"
          + "      \"City\": \"Ville\",\n"
          + "      \"Postal Code\": \"code postal\",\n"
          + "      \"Province\": \"Province\",\n"
          + "      \"District\": \"Quartier\",\n"
          + "      \"ZIP Code\": \"Code postal\",\n"
          + "      \"Greater area\": \"Grande zone\",\n"
          + "      \"Street\": \"rue\",\n"
          + "      \"Manufacturer\": \"Fabricant\",\n"
          + "      \"Covid 1D vaccine\": \"Vaccin Covid 1D\",\n"
          + "      \"Covid 2D vaccine\": \"Vaccin Covid 2D\",\n"
          + "      \"Covid 3D vaccine\": \"Vaccin Covid 3D\",\n"
          + "      \"Antwerpen\": \"Anvers\",\n"
          + "      \"Belgium\": \"Belgique\",\n"
          + "      \"Brussel\": \"Bruxelles\",\n"
          + "      \"English\": \"anglais\",\n"
          + "      \"French\": \"français\",\n"
          + "      \"Dutch\": \"néerlandais\",\n"
          + "      \"Bangalore clinic\": \"Hôpital de Bangalore\",\n"
          + "      \"Bogota General Hospital\": \"Hôpital Général de Bogota\"\n"
          + "    },\n"
          + "    \"nl\": {\n"
          + "      \"State\": \"Staat\",\n"
          + "      \"City\": \"stad\",\n"
          + "      \"Postal Code\": \"Postcode\",\n"
          + "      \"Province\": \"Provincie\",\n"
          + "      \"District\": \"Wijk\",\n"
          + "      \"ZIP Code\": \"Postcode\",\n"
          + "      \"Greater area\": \"Groter gebied\",\n"
          + "      \"Street\": \"Straat\",\n"
          + "      \"Manufacturer\": \"Fabrikant\",\n"
          + "      \"Covid 1D vaccine\": \"Covid 1D-vaccin\",\n"
          + "      \"Covid 2D vaccine\": \"Covid 2D-vaccin\",\n"
          + "      \"Covid 3D vaccine\": \"Covid 3D-vaccin\"\n"
          + "    },\n"
          + "    \"hi\": {\n"
          + "      \"State\": \"राज्य\",\n"
          + "      \"City\": \"शहर\",\n"
          + "      \"Postal Code\": \"डाक कोड\",\n"
          + "      \"Province\": \"प्रांत\",\n"
          + "      \"District\": \"जिला\",\n"
          + "      \"ZIP Code\": \"ज़िप कोड\",\n"
          + "      \"Greater area\": \"value2\",\n"
          + "      \"Street\": \"मार्ग\",\n"
          + "      \"Manufacturer\": \"उत्पादक\",\n"
          + "      \"Covid 1D vaccine\": \"कोविद 1 डी वैक्सीन\",\n"
          + "      \"Covid 2D vaccine\": \"कोविद 2 डी वैक्सीन\",\n"
          + "      \"Covid 3D vaccine\": \"कोविद 3 डी वैक्सीन\"\n"
          + "    }\n"
          + "  }\n"
          + "}";

  private static final String BIOMETRIC_API_CONFIG_NAME = "biometric.api.config.main";
  private static final String BIOMETRIC_API_CONFIG_DESC = "";
  private static final String BIOMETRIC_API_CONFIG_INIT_VALUE =
      "{\n"
          + "\"syncScope\":\"site\",\n"
          + "   \"operatorCredentialsRetentionTime\":86400000,\n"
          + "   \"operatorOfflineSessionTimeout\":86400000,\n"
          + "   \"vaccine\":[\n"
          + "      {\n"
          + "         \"name\":\"Vacc1\",\n"
          + "         \"manufacturers\":[\n"
          + "            \"JNJ\"\n"
          + "         ]\n"
          + "      }\n"
          + "   ],\n"
          + "   \"canUseDifferentManufacturers\":true,\n"
          + "   \"manufacturers\":[\n"
          + "      {\n"
          + "         \"name\":\"JNJ\",\n"
          + "         \"barcodeRegex\":\".*\"\n"
          + "      }\n"
          + "   ],\n"
          + "   \"personLanguages\":[\n"
          + "      {\n"
          + "         \"name\":\"English\"\n"
          + "      }\n"
          + "   ],\n"
          + "   \"authSteps\":[\n"
          + "      {\n"
          + "         \"mandatory\":false,\n"
          + "         \"type\":\"id_card\"\n"
          + "      },\n"
          + "      {\n"
          + "         \"mandatory\":false,\n"
          + "         \"type\":\"phone\"\n"
          + "      },\n"
          + "      {\n"
          + "         \"mandatory\":false,\n"
          + "         \"type\":\"iris_scan\"\n"
          + "      }\n"
          + "   ],\n"
          + "   \"irisScore\":50,\n"
          + "   \"addressFields\":{\n"
          + "      \"Belgium\":[\n"
          + "         {\n"
          + "            \"field\":\"cityVillage\",\n"
          + "            \"type\":\"DROPDOWN\",\n"
          + "            \"name\":\"City\",\n"
          + "            \"displayOrder\":1\n"
          + "         },\n"
          + "         {\n"
          + "            \"field\":\"stateProvince\",\n"
          + "            \"type\":\"DROPDOWN\",\n"
          + "            \"name\":\"Postalcode\",\n"
          + "            \"displayOrder\":2\n"
          + "         },\n"
          + "         {\n"
          + "            \"field\":\"address1\",\n"
          + "            \"type\":\"FREE_INPUT\",\n"
          + "            \"name\":\"Street\",\n"
          + "            \"displayOrder\":3\n"
          + "         },\n"
          + "         {\n"
          + "            \"field\":\"address2\",\n"
          + "            \"type\":\"FREE_INPUT\",\n"
          + "            \"name\":\"Number\",\n"
          + "            \"displayOrder\":4\n"
          + "         }\n"
          + "      ],\n"
          + "      \"United States of America\":[\n"
          + "         {\n"
          + "            \"field\":\"cityVillage\",\n"
          + "            \"type\":\"DROPDOWN\",\n"
          + "            \"name\":\"State\",\n"
          + "            \"displayOrder\":1\n"
          + "         },\n"
          + "         {\n"
          + "            \"field\":\"stateProvince\",\n"
          + "            \"type\":\"DROPDOWN\",\n"
          + "            \"name\":\"City\",\n"
          + "            \"displayOrder\":2\n"
          + "         },\n"
          + "         {\n"
          + "            \"field\":\"address1\",\n"
          + "            \"type\":\"FREE_INPUT\",\n"
          + "            \"name\":\"Postcode\",\n"
          + "            \"displayOrder\":3\n"
          + "         },\n"
          + "         {\n"
          + "            \"field\":\"address2\",\n"
          + "            \"type\":\"FREE_INPUT\",\n"
          + "            \"name\":\"Street\",\n"
          + "            \"displayOrder\":4\n"
          + "         }\n"
          + "      ]\n"
          + "   },\n"
          + "   \"allowManualParticipantIDEntry\":true,\n"
          + "   \"participantIDRegex\":\"\"\n"
          + "}";

  private static final String BIOMETRIC_API_CONFIG_VERSION_NAME = "biometric.api.config.version";
  private static final String BIOMETRIC_API_CONFIG_VERSION_DESC =
      "Specifies the app version details";
  private static final String BIOMETRIC_API_CONFIG_VERSION_INIT_VALUE =
      "{\n" + "  \"version\": \"\",\n" + "  \"url\": \"\"\n" + "}";

  private static final String VACCINATION_INFORMATION_ENABLED_VMP_VALUE = "true";

  private static final String BIOMETRIC_API_CONFIG_SUBSTANCES_CONFIG_NAME =
      "biometric.api.config.substances";
  private static final String BIOMETRIC_API_CONFIG_SUBSTANCES_CONFIG_DESC =
      "Configuration for vaccines and vitamins that should be administered for child at specific time";
  private static final String BIOMETRIC_API_CONFIG_SUBSTANCES_CONFIG_DEFAULT_VALUE =
      "[\n"
          + "   {\n"
          + "      \"conceptName\":\"Hep B BD Vxnaid\",\n"
          + "      \"label\":\"Hep B BD\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":5,\n"
          + "      \"maximumAgeInWeeks\":6,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"Hep B BD\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Polio 0 Vxnaid\",\n"
          + "      \"label\":\"Polio 0\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":3,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"Polio\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"BCG Vxnaid\",\n"
          + "      \"label\":\"BCG\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"BCG\",\n"
          + "      \"routeOfAdministration\":\"intradermal right upper arm\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Polio 1 Vxnaid\",\n"
          + "      \"label\":\"Polio 1\",\n"
          + "      \"weeksAfterBirth\":6,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Polio\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Rota 1 Vxnaid\",\n"
          + "      \"label\":\"Rota 1\",\n"
          + "      \"weeksAfterBirth\":6,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":104,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"Rota\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"PCV 1 Vxnaid\",\n"
          + "      \"label\":\"PCV 1\",\n"
          + "      \"weeksAfterBirth\":6,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"PCV\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Right Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"IPV 1 Vxnaid\",\n"
          + "      \"label\":\"IPV 1\",\n"
          + "      \"weeksAfterBirth\":6,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":7,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"IPV\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"DPT-HepB-Hib 1 Vxnaid\",\n"
          + "      \"label\":\"DPT-HepB-Hib 1\",\n"
          + "      \"weeksAfterBirth\":6,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"DPT\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Left Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Polio 2 Vxnaid\",\n"
          + "      \"label\":\"Polio 2\",\n"
          + "      \"weeksAfterBirth\":10,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Polio\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Rota 2 Vxnaid\",\n"
          + "      \"label\":\"Rota 2\",\n"
          + "      \"weeksAfterBirth\":10,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":104,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Rota\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"PCV 2 Vxnaid\",\n"
          + "      \"label\":\"PCV 2\",\n"
          + "      \"weeksAfterBirth\":10,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"PCV\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Right Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"DPT-HepB-Hib 2 Vxnaid\",\n"
          + "      \"label\":\"DPT-HepB-Hib 2\",\n"
          + "      \"weeksAfterBirth\":10,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"DPT\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Left Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Polio 3 Vxnaid\",\n"
          + "      \"label\":\"Polio 3\",\n"
          + "      \"weeksAfterBirth\":14,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Polio\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"PCV 3 Vxnaid\",\n"
          + "      \"label\":\"PCV 3\",\n"
          + "      \"weeksAfterBirth\":14,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"PCV\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Right Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"IPV 2 Vxnaid\",\n"
          + "      \"label\":\"IPV 2\",\n"
          + "      \"weeksAfterBirth\":14,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"IPV\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Right Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"DPT-HepB-Hib 3 Vxnaid\",\n"
          + "      \"label\":\"DPT-HepB-Hib 3\",\n"
          + "      \"weeksAfterBirth\":14,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"DPT\",\n"
          + "      \"routeOfAdministration\":\"IM-outer Upper Left Thigh\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Rota 3 Vxnaid\",\n"
          + "      \"label\":\"Rota 3\",\n"
          + "      \"weeksAfterBirth\":14,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":90,\n"
          + "      \"maximumAgeInWeeks\":104,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Rota\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Malaria 1 Vxnaid\",\n"
          + "      \"label\":\"Malaria 1\",\n"
          + "      \"weeksAfterBirth\":24,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"Malaria\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Vitamin A Vxnaid\",\n"
          + "      \"label\":\"Vitamin A\",\n"
          + "      \"weeksAfterBirth\":24,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Vitamins\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Malaria 2 Vxnaid\",\n"
          + "      \"label\":\"Malaria 2\",\n"
          + "      \"weeksAfterBirth\":28,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":2,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Malaria\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Malaria 3 Vxnaid\",\n"
          + "      \"label\":\"Malaria 3\",\n"
          + "      \"weeksAfterBirth\":32,\n"
          + "      \"weeksAfterBirthLowWindow\":2,\n"
          + "      \"weeksAfterBirthUpWindow\":40,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Malaria\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Measles Rubella 1 (MR1) Vxnaid\",\n"
          + "      \"label\":\"Measles Rubella 1 (MR1)\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":0,\n"
          + "      \"weeksAfterBirthUpWindow\":36,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"MR\",\n"
          + "      \"routeOfAdministration\":\"Subcutaneous Left Upper Arm\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Yellow Fever Vxnaid\",\n"
          + "      \"label\":\"Yellow fever\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"Fever\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Vitamin A Vxnaid\",\n"
          + "      \"label\":\"Vitamin A\",\n"
          + "      \"weeksAfterBirth\":48,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Vitamins\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Deworming Vxnaid\",\n"
          + "      \"label\":\"Deworming\",\n"
          + "      \"weeksAfterBirth\":48,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Vitamins\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Malaria 4 Vxnaid\",\n"
          + "      \"label\":\"Malaria 4\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"Malaria\",\n"
          + "      \"routeOfAdministration\":\"Oral\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Measles Rubella 2 (MR2) Vxnaid\",\n"
          + "      \"label\":\"Measles Rubella 2 (MR2)\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"MR\",\n"
          + "      \"routeOfAdministration\":\"Subcutaneous Left Upper Arm\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Vitamin A Vxnaid\",\n"
          + "      \"label\":\"Vitamin A\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Vitamins\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Deworming Vxnaid\",\n"
          + "      \"label\":\"Deworming\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Vitamins\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"HPV 1 Vxnaid\",\n"
          + "      \"label\":\"HPV 1\",\n"
          + "      \"weeksAfterBirth\":480,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":null,\n"
          + "      \"group\":\"HPV\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"HPV 2 Vxnaid\",\n"
          + "      \"label\":\"HPV 2\",\n"
          + "      \"weeksAfterBirth\":480,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":999,\n"
          + "      \"maximumAgeInWeeks\":null,\n"
          + "      \"minimumWeeksNumberAfterPreviousDose\":4,\n"
          + "      \"group\":\"HPV\",\n"
          + "      \"routeOfAdministration\":\"\",\n"
          + "      \"category\":\"Immunization\"\n"
          + "   }\n"
          + "]";

  private static final String BIOMETRIC_API_CONFIG_OTHER_SUBSTANCES_CONFIG_NAME =
      "biometric.api.config.otherSubstances";
  private static final String BIOMETRIC_API_CONFIG_OTHER_SUBSTANCES_CONFIG_DESC =
      "Configuration for other substances/medical examinations that should be administered for child at specific time";
  private static final String BIOMETRIC_API_CONFIG_OTHER_SUBSTANCES_CONFIG_DEFAULT_VALUE =
      "[\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Protection at birth for TT Vxnaid\",\n"
          + "      \"label\":\"Protection at birth for TT\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Protection at birth\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"Yes\",\n"
          + "         \"No\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Received LLIN Vxnaid\",\n"
          + "      \"label\":\"Received LLIN\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"LLIN\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Infant and young child feeding Vxnaid\",\n"
          + "      \"label\":\"Infant and young child feeding\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Feeding\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"EBF-Exclusive Breast Feeding\",\n"
          + "         \"RF-Replacement Feeding (never breastfed)\",\n"
          + "         \"MF-Mixed Feeding <6months)\",\n"
          + "         \"CF-Complementary Feeding (>6months)\",\n"
          + "         \"Weaning (<2 years)\",\n"
          + "         \"NBF-No longer Breastfeeding\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Infant HIV Screening Vxnaid\",\n"
          + "      \"label\":\"Infant HIV Screening\",\n"
          + "      \"weeksAfterBirth\":1,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"HIV Screening\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"Y - Infant Exposed\",\n"
          + "         \"N - No exposure\",\n"
          + "         \"NA - Not screened\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":6,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":10,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":14,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":24,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Infant and young child feeding Vxnaid\",\n"
          + "      \"label\":\"Infant and young child feeding\",\n"
          + "      \"weeksAfterBirth\":24,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Feeding\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"EBF-Exclusive Breast Feeding\",\n"
          + "         \"RF-Replacement Feeding (never breastfed)\",\n"
          + "         \"MF-Mixed Feeding <6months)\",\n"
          + "         \"CF-Complementary Feeding (>6months)\",\n"
          + "         \"Weaning (<2 years)\",\n"
          + "         \"NBF-No longer Breastfeeding\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Infant and young child feeding Vxnaid\",\n"
          + "      \"label\":\"Infant and young child feeding\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Feeding\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"EBF-Exclusive Breast Feeding\",\n"
          + "         \"RF-Replacement Feeding (never breastfed)\",\n"
          + "         \"MF-Mixed Feeding <6months)\",\n"
          + "         \"CF-Complementary Feeding (>6months)\",\n"
          + "         \"Weaning (<2 years)\",\n"
          + "         \"NBF-No longer Breastfeeding\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Age (weeks)\",\n"
          + "      \"label\":\"Age\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight for age Z score\",\n"
          + "      \"label\":\"Weight for age Z score\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"N-Normal (-2SD and +2SD)\",\n"
          + "         \"U-Underweight (-3SD and -2SD)\",\n"
          + "         \"SU-Severely Underweight (<-3SD)\",\n"
          + "         \"OW-Overweight (+3SD and +2SD)\",\n"
          + "         \"O-Obese (>+3SD )\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Height for age Z score Vxnaid\",\n"
          + "      \"label\":\"Height for age Z score\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"N-Normal (-2SD and above)\",\n"
          + "         \"S-Stunting (less than -2SD)\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"MUACA Vxnaid\",\n"
          + "      \"label\":\"MUACA\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"Red\",\n"
          + "         \"Yellow\",\n"
          + "         \"Green\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight for Height Vxnaid\",\n"
          + "      \"label\":\"Weight for Height\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"G-Normal Nutritional Status (egual or above -2SD)\",\n"
          + "         \"Y-Moderate Acute Malnutrition (MAM) (equal or less than -2SD but not to equal or less than -3SD)\",\n"
          + "         \"R-O, -Severe Acute Malnutrition (SAM) with Odema (less than or equal to -3SD)\",\n"
          + "         \"R-WO, SAM without Odema (less than or equal to -3SD)\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"INR Number Vxnaid\",\n"
          + "      \"label\":\"INR Number\",\n"
          + "      \"weeksAfterBirth\":36,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":48,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Infant and young child feeding Vxnaid\",\n"
          + "      \"label\":\"Infant and young child feeding\",\n"
          + "      \"weeksAfterBirth\":48,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Feeding\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"EBF-Exclusive Breast Feeding\",\n"
          + "         \"RF-Replacement Feeding (never breastfed)\",\n"
          + "         \"MF-Mixed Feeding <6months)\",\n"
          + "         \"CF-Complementary Feeding (>6months)\",\n"
          + "         \"Weaning (<2 years)\",\n"
          + "         \"NBF-No longer Breastfeeding\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight (kg)\",\n"
          + "      \"label\":\"Weight\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Growth Monitoring\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Infant and young child feeding Vxnaid\",\n"
          + "      \"label\":\"Infant and young child feeding\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Feeding\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"EBF-Exclusive Breast Feeding\",\n"
          + "         \"RF-Replacement Feeding (never breastfed)\",\n"
          + "         \"MF-Mixed Feeding <6months)\",\n"
          + "         \"CF-Complementary Feeding (>6months)\",\n"
          + "         \"Weaning (<2 years)\",\n"
          + "         \"NBF-No longer Breastfeeding\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight for age Z score\",\n"
          + "      \"label\":\"Weight for age Z score\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"N-Normal (-2SD and +2SD)\",\n"
          + "         \"U-Underweight (-3SD and -2SD)\",\n"
          + "         \"SU-Severely Underweight (<-3SD)\",\n"
          + "         \"OW-Overweight (+3SD and +2SD)\",\n"
          + "         \"O-Obese (>+3SD )\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Height for age Z score Vxnaid\",\n"
          + "      \"label\":\"Height for Age\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"N-Normal (-2SD and above)\",\n"
          + "         \"S-Stunting (less than -2SD)\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"MUACA Vxnaid\",\n"
          + "      \"label\":\"MUACA\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"Red\",\n"
          + "         \"Yellow\",\n"
          + "         \"Green\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\"Weight for Height Vxnaid\",\n"
          + "      \"label\":\"Weight for Height\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"radio\",\n"
          + "      \"options\":[\n"
          + "         \"G-Normal Nutritional Status (egual or above -2SD)\",\n"
          + "         \"Y-Moderate Acute Malnutrition (MAM) (equal or less than -2SD but not to equal or less than -3SD)\",\n"
          + "         \"R-O, -Severe Acute Malnutrition (SAM) with Odema (less than or equal to -3SD)\",\n"
          + "         \"R-WO, SAM without Odema (less than or equal to -3SD)\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"conceptName\":\" INR Number Vxnaid\",\n"
          + "      \"label\":\"INR Number\",\n"
          + "      \"weeksAfterBirth\":72,\n"
          + "      \"weeksAfterBirthLowWindow\":1,\n"
          + "      \"weeksAfterBirthUpWindow\":1,\n"
          + "      \"category\":\"Nutrition assessment\",\n"
          + "      \"inputType\":\"text\",\n"
          + "      \"options\":[\n"
          + "         \n"
          + "      ]\n"
          + "   }\n"
          + "]";

  private static final String BIOMETRIC_API_CONFIG_SUBSTANCE_GROUPS_CONFIG_NAME =
      "biometric.api.config.substanceGroups";
  private static final String BIOMETRIC_API_CONFIG_SUBSTANCE_GROUPS_DESC =
      "Used to collect info about substances and its elements e.g. Polio consists of Polio 1, Polio 2, Polio 3, Polio 4";
  private static final String BIOMETRIC_API_CONFIG_SUBSTANCE_GROUPS_DEFAULT_VALUE =
      "[\n"
          + "   {\n"
          + "      \"substanceName\":\"Hep B BD\",\n"
          + "      \"options\":[\n"
          + "         \"Hep B BD Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"Polio\",\n"
          + "      \"options\":[\n"
          + "         \"Polio 0 Vxnaid\",\n"
          + "         \"Polio 1 Vxnaid\",\n"
          + "         \"Polio 2 Vxnaid\",\n"
          + "         \"Polio 3 Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"BCG\",\n"
          + "      \"options\":[\n"
          + "         \"BCG Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"Rota\",\n"
          + "      \"options\":[\n"
          + "         \"Rota 1 Vxnaid\",\n"
          + "         \"Rota 2 Vxnaid\",\n"
          + "         \"Rota 3 Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"PCV\",\n"
          + "      \"options\":[\n"
          + "         \"PCV 1 Vxnaid\",\n"
          + "         \"PCV 2 Vxnaid\",\n"
          + "         \"PCV 3 Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"DPT\",\n"
          + "      \"options\":[\n"
          + "         \"DPT-HepB-Hib 1 Vxnaid\",\n"
          + "         \"DPT-HepB-Hib 2 Vxnaid\",\n"
          + "         \"DPT-HepB-Hib 3 Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"IPV\",\n"
          + "      \"options\":[\n"
          + "         \"IPV 1 Vxnaid\",\n"
          + "         \"IPV 2 Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"MR\",\n"
          + "      \"options\":[\n"
          + "         \"Measles Rubella 1 (MR1) Vxnaid\",\n"
          + "         \"Measles Rubella 2 (MR2) Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"Fever\",\n"
          + "      \"options\":[\n"
          + "         \"Yellow Fever Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"HPV\",\n"
          + "      \"options\":[\n"
          + "         \"HPV 1 Vxnaid\",\n"
          + "         \"HPV 2 Vxnaid\"\n"
          + "      ]\n"
          + "   },\n"
          + "   {\n"
          + "      \"substanceName\":\"Malaria\",\n"
          + "      \"options\":[\n"
          + "         \"Malaria 1 Vxnaid\",\n"
          + "         \"Malaria 2 Vxnaid\",\n"
          + "         \"Malaria 3 Vxnaid\",\n"
          + "         \"Malaria 4 Vxnaid\"\n"
          + "      ]\n"
          + "   }\n"
          + "]";

  @Override
  public int getVersion() {
    return 3;
  }

  @Override
  protected void installEveryTime() {
    // Ensures the Vxnaid app works correctly with CFL BE
    install(
        globalProperty(
            GlobalPropertiesConstants.SHOULD_CREATE_FIRST_VISIT.getKey(),
            GlobalPropertiesConstants.SHOULD_CREATE_FIRST_VISIT.getDescription(),
            "false"));
    install(
        globalProperty(
            GlobalPropertiesConstants.SHOULD_CREATE_FUTURE_VISITS.getKey(),
            GlobalPropertiesConstants.SHOULD_CREATE_FUTURE_VISITS.getDescription(),
            "true"));
  }

  @Override
  protected void installNewVersion() {
    install(
        globalProperty(
            BIOMETRIC_ENABLE_BIOMETRIC_FEATURE_NAME,
            BIOMETRIC_ENABLE_BIOMETRIC_FEATURE_DESC,
            BIOMETRIC_ENABLE_BIOMETRIC_FEATURE_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_ENABLE_MFA_NAME, BIOMETRIC_ENABLE_MFA_DESC, BIOMETRIC_ENABLE_MFA_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_SERVER_URL_NAME, BIOMETRIC_SERVER_URL_DESC, BIOMETRIC_SERVER_URL_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_ADMIN_PORT_NAME, BIOMETRIC_ADMIN_PORT_DESC, BIOMETRIC_ADMIN_PORT_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_CLIENT_PORT_NAME,
            BIOMETRIC_CLIENT_PORT_DESC,
            BIOMETRIC_CLIENT_PORT_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_EXTRACTOR_LICENSE_NAME,
            BIOMETRIC_EXTRACTOR_LICENSE_DESC,
            BIOMETRIC_EXTRACTOR_LICENSE_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_IMPLEMENTATION_CONFIG_NAME,
            BIOMETRIC_IMPLEMENTATION_CONFIG_DESC,
            BIOMETRIC_IMPLEMENTATION_CONFIG_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_MATCHING_THRESHOLD_NAME,
            BIOMETRIC_MATCHING_THRESHOLD_DESC,
            BIOMETRIC_MATCHING_THRESHOLD_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_API_CONFIG_LOCALIZATION_NAME,
            BIOMETRIC_API_CONFIG_LOCALIZATION_DESC,
            BIOMETRIC_API_CONFIG_LOCALIZATION_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_API_CONFIG_NAME, BIOMETRIC_API_CONFIG_DESC, BIOMETRIC_API_CONFIG_INIT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_API_CONFIG_VERSION_NAME,
            BIOMETRIC_API_CONFIG_VERSION_DESC,
            BIOMETRIC_API_CONFIG_VERSION_INIT_VALUE));
    install(
        globalProperty(
            CFLConstants.VACCINATION_LISTENER_KEY,
            CFLConstants.VACCINATION_LISTENER_DESCRIPTION,
            CFLConstants.VACCINATION_VISIT_LISTENER_NAME));
    install(
        globalProperty(
            CFLConstants.VACCINATION_INFORMATION_ENABLED_KEY,
            CFLConstants.VACCINATION_INFORMATION_ENABLED_KEY_DESCRIPTION,
            VACCINATION_INFORMATION_ENABLED_VMP_VALUE));
    install(
        globalProperty(
            BIOMETRIC_API_CONFIG_SUBSTANCES_CONFIG_NAME,
            BIOMETRIC_API_CONFIG_SUBSTANCES_CONFIG_DESC,
            BIOMETRIC_API_CONFIG_SUBSTANCES_CONFIG_DEFAULT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_API_CONFIG_OTHER_SUBSTANCES_CONFIG_NAME,
            BIOMETRIC_API_CONFIG_OTHER_SUBSTANCES_CONFIG_DESC,
            BIOMETRIC_API_CONFIG_OTHER_SUBSTANCES_CONFIG_DEFAULT_VALUE));
    install(
        globalProperty(
            BIOMETRIC_API_CONFIG_SUBSTANCE_GROUPS_CONFIG_NAME,
            BIOMETRIC_API_CONFIG_SUBSTANCE_GROUPS_DESC,
            BIOMETRIC_API_CONFIG_SUBSTANCE_GROUPS_DEFAULT_VALUE));
  }
}
